# Generated by Django 4.1.1 on 2023-04-06 07:55

import Products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('discription', models.TextField()),
                ('rate', models.IntegerField()),
                ('category', models.CharField(choices=[('Leisure', 'Leisure'), ('Sports', 'Sports')], default='Leisure', max_length=10)),
                ('dimension', models.CharField(max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to=Products.models.Products.nameFile)),
            ],
        ),
    ]
